### ISSUE TITLE
Potential inconsistency between `builtins.type` and `typing.Type`

### ISSUE THREAD

**Issue by mirceamironenco** [brentyi/tyro#164]
Is the way `type` and `Type` are treated differently a result of my faulty usage, how tyro deals with typevars or just a general [inconsistency with the typing system](https://discuss.python.org/t/inconsistencies-between-type-and-type/37404)? On tyro 0.8.11:

```py
from dataclasses import dataclass, field
from typing import Type

import tyro


class Thing: ...


class SubThing(Thing): ...


@dataclass
class Config:
    foo: int
    # fails
    bar: type[Thing] = field(default_factory=lambda: SubThing)

    # works
    # bar: Type[Thing] = field(default_factory=lambda: SubThing)


if __name__ == "__main__":
    tyro.cli(Config)
```
I was assuming since `typing.Type` is a deprecated alias of `type` this usage would be fine. Sorry if this is documented somewhere and I missed it.

**Comment by brentyi** [comment]
No, this is a bug. Thanks for catching it! I'll get the fix merged/released today.

**Comment by mirceamironenco** [comment]
Hi @brentyi, thanks for the fast response and fix! If you don't mind I have one more inconsistency I observed (with tyro installed from source to have the latest fix):

```py
# x.py
from dataclasses import dataclass, field
from typing import Type

import tyro


class Thing: ...


class SubThing(Thing): ...


@dataclass
class Config:
    foo: type = field(default_factory=lambda: SubThing)
    bar: Type = field(default_factory=lambda: SubThing)


if __name__ == "__main__":
    tyro.cli(Config)
```
Now if you run `py x.py -h` it seems that `bar` is `fixed`, while `foo` is `TYPE` (and not fixed). As a potential use-case wher ethis might come up, if one uses `tyro.cli(tyro.conf.SuppressFixed[Config])` only `bar` would be supressed.

**Comment by brentyi** [comment]
Thanks @mirceamironenco! I just fixed this too. Unfortunately these specific discrepancies do just require special-cases, `type` was being handled differently because we detect that it's callable (whereas `Type` isn't callable).

**Comment by mirceamironenco** [comment]
Great! Your comment regarding what is and isn't callable made me think of another corner case and it seems something is different again. I don't really have a use-case in mind for this one,  but maybe it helps you notice something that might still need to be addressed by the underlying implementation:

```py
# x.py
from dataclasses import dataclass, field
from typing import Type

import tyro


@dataclass
class Config:
    # works
    # bar: type = field(default_factory=lambda: type)

    # fails
    # bar: type = field(default_factory=lambda: Type)

    # fails
    # bar: Type = field(default_factory=lambda: Type)

    # works
    bar: Type = field(default_factory=lambda: type)


if __name__ == "__main__":
    tyro.cli(Config)
```
On latest tyro I get `TypeError: '_SpecialGenericAlias' object is not iterable`.

**Comment by brentyi** [comment]
Fixed this too, thanks!

Turns out `Type` has an interesting property where `hasattr(Type, "__iter__")` is `True` but you get that `TypeError` if you actually try to iterate over it.
